"""create initial schema

Revision ID: bcb56dd71d89
Revises: 
Create Date: 2026-09-03 14:05:10.758134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb56dd71d89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_discord_user_id'), 'users', ['discord_user_id'], unique=True)
    op.create_table('game_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_accounts_game_id_games'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_accounts')),
    sa.UniqueConstraint('game_id', 'external_id', name='uq_game_accounts_game_external_id')
    )
    op.create_index(op.f('ix_game_accounts_game_id'), 'game_accounts', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_accounts_user_id'), 'game_accounts', ['user_id'], unique=False)
    op.create_table('player_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_account_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_account_id'], ['game_accounts.id'], name=op.f('fk_player_profiles_game_account_id_game_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_profiles'))
    )
    op.create_index(op.f('ix_player_profiles_game_account_id'), 'player_profiles', ['game_account_id'], unique=False)
    op.create_table('profiling_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_account_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_account_id'], ['game_accounts.id'], name=op.f('fk_profiling_jobs_game_account_id_game_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiling_jobs'))
    )
    op.create_index(op.f('ix_profiling_jobs_game_account_id'), 'profiling_jobs', ['game_account_id'], unique=False)
    op.create_index(op.f('ix_profiling_jobs_status'), 'profiling_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiling_jobs_status'), table_name='profiling_jobs')
    op.drop_index(op.f('ix_profiling_jobs_game_account_id'), table_name='profiling_jobs')
    op.drop_table('profiling_jobs')
    op.drop_index(op.f('ix_player_profiles_game_account_id'), table_name='player_profiles')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_game_accounts_user_id'), table_name='game_accounts')
    op.drop_index(op.f('ix_game_accounts_game_id'), table_name='game_accounts')
    op.drop_table('game_accounts')
    op.drop_index(op.f('ix_users_discord_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
